# Generated by Django 3.2.8 on 2021-12-29 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211228_0010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answers_count',
            new_name='rate',
        ),
    ]
