# Generated by Django 3.2.8 on 2021-12-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_comment_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='correct',
            field=models.BooleanField(default=False),
        ),
    ]
